version: '3.8'

networks:
  app_network:
    external: true

services:
    
  db_node_1:
    container_name: db_node_1
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - "9081:8080"
    volumes:
      - /opt/storage/node1:/opt/storage/

  db_node_2:
    container_name: db_node_2
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - "9082:8080"
    volumes:
      - /opt/storage/node2:/opt/storage/

  db_node_3:
    container_name: db_node_3
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - "9083:8080"
    volumes:
      - /opt/storage/node3:/opt/storage/

