version: '3.8'

networks:
  app_network:
    external: true

services:
  # server:
  #   container_name: server 
  #   build:
  #     context: ./router
  #     dockerfile: Dockerfile
  #   ports:
  #     - "1444:1444"
  #   image: router
  #   networks:
  #     app_network:
  #       ipv4_address: 172.16.1.4
    

  db_node_1:
    container_name: db_node_1
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - "9081:8080"
    # networks:
      # app_network:
        # ipv4_address: 172.16.1.6

  db_node_2:
    container_name: db_node_2
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - "9082:8080"
    # networks:
    #   app_network:
    #     ipv4_address: 172.16.1.7

  db_node_3:
    container_name: db_node_3
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - "9083:8080"
    # networks:
      # app_network:
        # ipv4_address: 172.16.1.8

